# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dolphin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QWidget, QVBoxLayout, QPushButton, QFileDialog , QLabel, QTextEdit
from PyQt5.QtGui import QPixmap
import dolphinVsWhale

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.consoleLog = QtWidgets.QScrollArea(self.centralwidget)
        self.consoleLog.setGeometry(QtCore.QRect(20, 20, 301, 401))
        self.consoleLog.setWidgetResizable(True)
        self.consoleLog.setObjectName("consoleLog")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.consoleLog.setWidget(self.scrollAreaWidgetContents)
        self.compileAction = QtWidgets.QPushButton(self.centralwidget)
        self.compileAction.setGeometry(QtCore.QRect(360, 310, 101, 41))
        self.compileAction.setObjectName("compileAction")
        self.testBestModel = QtWidgets.QPushButton(self.centralwidget)
        self.testBestModel.setGeometry(QtCore.QRect(500, 310, 101, 41))
        self.testBestModel.setObjectName("testBestModel")
        self.testCurrent = QtWidgets.QPushButton(self.centralwidget)
        self.testCurrent.setGeometry(QtCore.QRect(500, 370, 101, 41))
        self.testCurrent.setObjectName("testCurrent")
        self.loadBest = QtWidgets.QPushButton(self.centralwidget)
        self.loadBest.setGeometry(QtCore.QRect(360, 370, 101, 41))
        self.loadBest.setObjectName("loadBest")
        self.labelPhoto = QtWidgets.QLabel(self.centralwidget)
        self.labelPhoto.setGeometry(QtCore.QRect(330, 90, 301, 151))
        self.labelPhoto.setText("")
        self.labelPhoto.setPixmap(QtGui.QPixmap("G:/biai/ds/single_test/0.jpg"))
        self.labelPhoto.setScaledContents(True)
        self.labelPhoto.setObjectName("labelPhoto")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(330, 20, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Image = QtWidgets.QAction(MainWindow)
        self.actionAdd_Image.setObjectName("actionAdd_Image")
        self.actionAdd_Model = QtWidgets.QAction(MainWindow)
        self.actionAdd_Model.setObjectName("actionAdd_Model")
        self.menuFile.addAction(self.actionAdd_Image)
        self.menuFile.addAction(self.actionAdd_Model)
        self.menubar.addAction(self.menuFile.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionAdd_Image.triggered.connect(self.clickAddImg)

    def clickAddImg(self):
        filename = QFileDialog.getOpenFileName(self, 'Open File', 'G:/biai/ds/single_test/')#,"Image files (*.jpg)")
        fname = open(filename)
        data = fname.read()
        self.labelPhoto.setPixmap(QPixmap(data))
        fname.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.compileAction.setText(_translate("MainWindow", "Compile Model"))
        self.testBestModel.setText(_translate("MainWindow", "Test Model"))
        self.testBestModel.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.testCurrent.setText(_translate("MainWindow", "Test current image"))
        self.loadBest.setText(_translate("MainWindow", "Load Best Model"))
        self.title.setText(_translate("MainWindow", "Check if its a whale or a dolphin"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_Image.setText(_translate("MainWindow", "Add Image"))
        self.actionAdd_Image.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionAdd_Model.setText(_translate("MainWindow", "Add Model"))
        self.actionAdd_Model.setShortcut(_translate("MainWindow", "Ctrl+M"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
